### ISSUE TITLE
gbe.json?

### ISSUE THREAD

**Issue by Zeronimous** [brunolee-GIT/GSE-Generator#15]
Tried the app once, it ran well but after that use, i cant make it work. It goes normal until i put all the language settings and then this happen (image) .I'd tried to download again, with no result. 
What can i do to fix it?

![error](https://github.com/user-attachments/assets/46dab8cc-7599-4a89-b13b-20c56aef2055)

If i drag and drop the dll it just show the "searching emulator" text, with the same error

**Comment by brunolee-GIT** [comment]
For some reason GSE_Generator.bat cannot write to this location. (I think the cause is OneDrive)
GSE_Generator.bat uses the directory where it is to write temporary and final files.
Try change directory.

**Comment by Zeronimous** [comment]
It didnt seems to be the problem, have tried on another directories and even another partition but getting the same.

just an update info if it helps:

Im running it with 0 problems on a virtual machine, when i run it there for the 1's time i realized that in my pc i dont even see the game mini picture when u put the steam id of the game and in the vm is visible

**Comment by brunolee-GIT** [comment]
Clearly something is not letting the script write all the files.
From what I see in image, script can write one file and edit it, then can't write anymore.

Without further details I can only see 3 culprits: OneDrive; antivirus; user permissions
To eliminate the possibility of it being any these, try **turn off OneDrive and antivirus(es) and run the script as administrator**

I still think the problem is OneDrive or any other software you have for backup purposes.
It doesn't seem like an OS issue, but I could be wrong.

**Comment by Zeronimous** [comment]
Sorry about the late response! 

It was an Avast problem, such a noobie error by my side but avast didnt show me any notification anytime and  i checked the cuarentine and nothing there, was after reading u that i thought about trying with avast turned off.

Thanks for your time and ur work, have a great day!
